/// Curated list of common Indian grocery items for autocomplete suggestions.
/// Organised by category but stored as a flat list with category hints so the
/// form can also pre-fill the category dropdown when a suggestion is picked.
class GrocerySuggestions {
  const GrocerySuggestions._();

  /// Every suggestion: {name, category}.
  static const List<({String name, String category})> all = [
    // ── Vegetables ──────────────────────────────────────────────────────────
    (name: 'Aloo (Potato)', category: 'Fruits & Vegetables'),
    (name: 'Pyaaz (Onion)', category: 'Fruits & Vegetables'),
    (name: 'Tamatar (Tomato)', category: 'Fruits & Vegetables'),
    (name: 'Adrak (Ginger)', category: 'Fruits & Vegetables'),
    (name: 'Lahsun (Garlic)', category: 'Fruits & Vegetables'),
    (name: 'Hari Mirch (Green Chilli)', category: 'Fruits & Vegetables'),
    (name: 'Palak (Spinach)', category: 'Fruits & Vegetables'),
    (name: 'Methi (Fenugreek Leaves)', category: 'Fruits & Vegetables'),
    (name: 'Dhania (Coriander Leaves)', category: 'Fruits & Vegetables'),
    (name: 'Pudina (Mint)', category: 'Fruits & Vegetables'),
    (name: 'Gobhi (Cauliflower)', category: 'Fruits & Vegetables'),
    (name: 'Patta Gobhi (Cabbage)', category: 'Fruits & Vegetables'),
    (name: 'Baingan (Brinjal)', category: 'Fruits & Vegetables'),
    (name: 'Bhindi (Okra)', category: 'Fruits & Vegetables'),
    (name: 'Tori (Ridge Gourd)', category: 'Fruits & Vegetables'),
    (name: 'Lauki (Bottle Gourd)', category: 'Fruits & Vegetables'),
    (name: 'Karela (Bitter Gourd)', category: 'Fruits & Vegetables'),
    (name: 'Kaddu (Pumpkin)', category: 'Fruits & Vegetables'),
    (name: 'Shimla Mirch (Capsicum)', category: 'Fruits & Vegetables'),
    (name: 'Matar (Peas)', category: 'Fruits & Vegetables'),
    (name: 'Beans (French Beans)', category: 'Fruits & Vegetables'),
    (name: 'Gajar (Carrot)', category: 'Fruits & Vegetables'),
    (name: 'Mooli (Radish)', category: 'Fruits & Vegetables'),
    (name: 'Shalgam (Turnip)', category: 'Fruits & Vegetables'),
    (name: 'Shakarkand (Sweet Potato)', category: 'Fruits & Vegetables'),
    (name: 'Arbi (Colocasia)', category: 'Fruits & Vegetables'),
    (name: 'Suran (Yam)', category: 'Fruits & Vegetables'),
    (name: 'Kheera (Cucumber)', category: 'Fruits & Vegetables'),
    (name: 'Tinda (Apple Gourd)', category: 'Fruits & Vegetables'),
    (name: 'Parwal (Pointed Gourd)', category: 'Fruits & Vegetables'),
    (name: 'Drumstick (Sahjan)', category: 'Fruits & Vegetables'),
    (name: 'Raw Banana', category: 'Fruits & Vegetables'),
    (name: 'Lotus Root', category: 'Fruits & Vegetables'),
    (name: 'Spring Onion', category: 'Fruits & Vegetables'),
    (name: 'Leek', category: 'Fruits & Vegetables'),
    (name: 'Broccoli', category: 'Fruits & Vegetables'),
    (name: 'Zucchini', category: 'Fruits & Vegetables'),
    (name: 'Baby Corn', category: 'Fruits & Vegetables'),
    (name: 'Mushroom', category: 'Fruits & Vegetables'),
    (name: 'Curry Leaves', category: 'Fruits & Vegetables'),

    // ── Fruits ──────────────────────────────────────────────────────────────
    (name: 'Aam (Mango)', category: 'Fruits & Vegetables'),
    (name: 'Seb (Apple)', category: 'Fruits & Vegetables'),
    (name: 'Kela (Banana)', category: 'Fruits & Vegetables'),
    (name: 'Santra (Orange)', category: 'Fruits & Vegetables'),
    (name: 'Mosambi (Sweet Lime)', category: 'Fruits & Vegetables'),
    (name: 'Nimbu (Lemon)', category: 'Fruits & Vegetables'),
    (name: 'Anaar (Pomegranate)', category: 'Fruits & Vegetables'),
    (name: 'Angoor (Grapes)', category: 'Fruits & Vegetables'),
    (name: 'Tarbuz (Watermelon)', category: 'Fruits & Vegetables'),
    (name: 'Kharbooja (Muskmelon)', category: 'Fruits & Vegetables'),
    (name: 'Papita (Papaya)', category: 'Fruits & Vegetables'),
    (name: 'Amrood (Guava)', category: 'Fruits & Vegetables'),
    (name: 'Nashpati (Pear)', category: 'Fruits & Vegetables'),
    (name: 'Aalu Bukhara (Plum)', category: 'Fruits & Vegetables'),
    (name: 'Chikoo (Sapodilla)', category: 'Fruits & Vegetables'),
    (name: 'Jamun (Black Plum)', category: 'Fruits & Vegetables'),
    (name: 'Nariyal (Coconut)', category: 'Fruits & Vegetables'),
    (name: 'Kiwi', category: 'Fruits & Vegetables'),
    (name: 'Strawberry', category: 'Fruits & Vegetables'),
    (name: 'Pineapple', category: 'Fruits & Vegetables'),
    (name: 'Lychee', category: 'Fruits & Vegetables'),
    (name: 'Jackfruit', category: 'Fruits & Vegetables'),
    (name: 'Custard Apple', category: 'Fruits & Vegetables'),
    (name: 'Dragon Fruit', category: 'Fruits & Vegetables'),
    (name: 'Avocado', category: 'Fruits & Vegetables'),

    // ── Dairy & Eggs ────────────────────────────────────────────────────────
    (name: 'Doodh (Milk)', category: 'Dairy & Eggs'),
    (name: 'Dahi (Curd / Yogurt)', category: 'Dairy & Eggs'),
    (name: 'Paneer', category: 'Dairy & Eggs'),
    (name: 'Makhan (Butter)', category: 'Dairy & Eggs'),
    (name: 'Ghee', category: 'Dairy & Eggs'),
    (name: 'Malai (Cream)', category: 'Dairy & Eggs'),
    (name: 'Khoya / Mawa', category: 'Dairy & Eggs'),
    (name: 'Chach (Buttermilk)', category: 'Dairy & Eggs'),
    (name: 'Shrikhand', category: 'Dairy & Eggs'),
    (name: 'Anday (Eggs)', category: 'Dairy & Eggs'),
    (name: 'Cheese', category: 'Dairy & Eggs'),
    (name: 'Condensed Milk', category: 'Dairy & Eggs'),

    // ── Grains, Rice & Flour ─────────────────────────────────────────────
    (name: 'Chawal (Rice)', category: 'Pantry & Dry Goods'),
    (name: 'Basmati Rice', category: 'Pantry & Dry Goods'),
    (name: 'Atta (Wheat Flour)', category: 'Pantry & Dry Goods'),
    (name: 'Maida (All-purpose Flour)', category: 'Pantry & Dry Goods'),
    (name: 'Besan (Gram Flour)', category: 'Pantry & Dry Goods'),
    (name: 'Sooji / Rava (Semolina)', category: 'Pantry & Dry Goods'),
    (name: 'Poha (Flattened Rice)', category: 'Pantry & Dry Goods'),
    (name: 'Murmura (Puffed Rice)', category: 'Pantry & Dry Goods'),
    (name: 'Oats', category: 'Pantry & Dry Goods'),
    (name: 'Cornflour', category: 'Pantry & Dry Goods'),
    (name: 'Ragi Flour', category: 'Pantry & Dry Goods'),
    (name: 'Jowar Flour', category: 'Pantry & Dry Goods'),
    (name: 'Bajra Flour', category: 'Pantry & Dry Goods'),
    (name: 'Bread', category: 'Bakery'),
    (name: 'Brown Bread', category: 'Bakery'),
    (name: 'Pav (Buns)', category: 'Bakery'),
    (name: 'Rusk', category: 'Bakery'),

    // ── Lentils & Pulses ────────────────────────────────────────────────────
    (name: 'Toor Dal (Arhar)', category: 'Pantry & Dry Goods'),
    (name: 'Moong Dal', category: 'Pantry & Dry Goods'),
    (name: 'Masoor Dal (Red Lentil)', category: 'Pantry & Dry Goods'),
    (name: 'Chana Dal', category: 'Pantry & Dry Goods'),
    (name: 'Urad Dal', category: 'Pantry & Dry Goods'),
    (name: 'Rajma (Kidney Beans)', category: 'Pantry & Dry Goods'),
    (name: 'Chole (Chickpeas)', category: 'Pantry & Dry Goods'),
    (name: 'Kala Chana (Black Chickpeas)', category: 'Pantry & Dry Goods'),
    (name: 'Kabuli Chana (White Chickpeas)', category: 'Pantry & Dry Goods'),
    (name: 'Moth Beans', category: 'Pantry & Dry Goods'),
    (name: 'Lobiya (Black-eyed Peas)', category: 'Pantry & Dry Goods'),
    (name: 'Val (Broad Beans)', category: 'Pantry & Dry Goods'),

    // ── Spices & Condiments ─────────────────────────────────────────────────
    (name: 'Namak (Salt)', category: 'Pantry & Dry Goods'),
    (name: 'Cheeni (Sugar)', category: 'Pantry & Dry Goods'),
    (name: 'Haldi (Turmeric)', category: 'Pantry & Dry Goods'),
    (name: 'Lal Mirch (Red Chilli Powder)', category: 'Pantry & Dry Goods'),
    (name: 'Dhaniya Powder (Coriander Powder)', category: 'Pantry & Dry Goods'),
    (name: 'Jeera (Cumin Seeds)', category: 'Pantry & Dry Goods'),
    (name: 'Rai (Mustard Seeds)', category: 'Pantry & Dry Goods'),
    (name: 'Garam Masala', category: 'Pantry & Dry Goods'),
    (name: 'Amchur (Dry Mango Powder)', category: 'Pantry & Dry Goods'),
    (name: 'Imli (Tamarind)', category: 'Pantry & Dry Goods'),
    (name: 'Kala Namak (Black Salt)', category: 'Pantry & Dry Goods'),
    (name: 'Ajwain (Carom Seeds)', category: 'Pantry & Dry Goods'),
    (name: 'Methi Dana (Fenugreek Seeds)', category: 'Pantry & Dry Goods'),
    (name: 'Saunf (Fennel Seeds)', category: 'Pantry & Dry Goods'),
    (name: 'Hing (Asafoetida)', category: 'Pantry & Dry Goods'),
    (name: 'Elaichi (Cardamom)', category: 'Pantry & Dry Goods'),
    (name: 'Lavang (Cloves)', category: 'Pantry & Dry Goods'),
    (name: 'Dalchini (Cinnamon)', category: 'Pantry & Dry Goods'),
    (name: 'Tejpatta (Bay Leaves)', category: 'Pantry & Dry Goods'),
    (name: 'Kesar (Saffron)', category: 'Pantry & Dry Goods'),
    (name: 'Chat Masala', category: 'Pantry & Dry Goods'),
    (name: 'Sambhar Masala', category: 'Pantry & Dry Goods'),
    (name: 'Pav Bhaji Masala', category: 'Pantry & Dry Goods'),
    (name: 'Biryani Masala', category: 'Pantry & Dry Goods'),

    // ── Oils & Sauces ───────────────────────────────────────────────────────
    (name: 'Tel (Cooking Oil)', category: 'Pantry & Dry Goods'),
    (name: 'Sarson Tel (Mustard Oil)', category: 'Pantry & Dry Goods'),
    (name: 'Nariyal Tel (Coconut Oil)', category: 'Pantry & Dry Goods'),
    (name: 'Olive Oil', category: 'Pantry & Dry Goods'),
    (name: 'Sirka (Vinegar)', category: 'Pantry & Dry Goods'),
    (name: 'Tomato Ketchup', category: 'Pantry & Dry Goods'),
    (name: 'Green Chutney', category: 'Pantry & Dry Goods'),
    (name: 'Soy Sauce', category: 'Pantry & Dry Goods'),

    // ── Meat & Seafood ──────────────────────────────────────────────────────
    (name: 'Murga (Chicken)', category: 'Meat & Seafood'),
    (name: 'Mutton', category: 'Meat & Seafood'),
    (name: 'Machli (Fish)', category: 'Meat & Seafood'),
    (name: 'Jhinga (Prawns)', category: 'Meat & Seafood'),
    (name: 'Rohu Fish', category: 'Meat & Seafood'),
    (name: 'Pomfret', category: 'Meat & Seafood'),
    (name: 'Surmai (King Fish)', category: 'Meat & Seafood'),
    (name: 'Egg (Boiled)', category: 'Meat & Seafood'),

    // ── Beverages ───────────────────────────────────────────────────────────
    (name: 'Chai (Tea)', category: 'Beverages'),
    (name: 'Coffee', category: 'Beverages'),
    (name: 'Nimbu Pani (Lemonade)', category: 'Beverages'),
    (name: 'Coconut Water', category: 'Beverages'),
    (name: 'Juice', category: 'Beverages'),
    (name: 'Cold Drink (Soda)', category: 'Beverages'),
    (name: 'Lassi', category: 'Beverages'),
    (name: 'Aam Panna', category: 'Beverages'),
    (name: 'Rooh Afza', category: 'Beverages'),

    // ── Snacks ──────────────────────────────────────────────────────────────
    (name: 'Biscuits', category: 'Snacks'),
    (name: 'Namkeen', category: 'Snacks'),
    (name: 'Sev', category: 'Snacks'),
    (name: 'Papad', category: 'Snacks'),
    (name: 'Chips', category: 'Snacks'),
    (name: 'Chakli', category: 'Snacks'),
    (name: 'Murmura (Puffed Rice Snack)', category: 'Snacks'),
    (name: 'Chivda', category: 'Snacks'),
    (name: 'Dry Fruits Mix', category: 'Snacks'),
    (name: 'Kaju (Cashew)', category: 'Snacks'),
    (name: 'Badam (Almonds)', category: 'Snacks'),
    (name: 'Akhrot (Walnuts)', category: 'Snacks'),
    (name: 'Kishmish (Raisins)', category: 'Snacks'),
    (name: 'Chocolate', category: 'Snacks'),

    // ── Frozen ──────────────────────────────────────────────────────────────
    (name: 'Frozen Matar (Peas)', category: 'Frozen'),
    (name: 'Frozen Corn', category: 'Frozen'),
    (name: 'Frozen Paratha', category: 'Frozen'),
    (name: 'Ice Cream', category: 'Frozen'),

    // ── Household ───────────────────────────────────────────────────────────
    (name: 'Sabun (Soap)', category: 'Household'),
    (name: 'Shampoo', category: 'Household'),
    (name: 'Toothpaste', category: 'Household'),
    (name: 'Toothbrush', category: 'Household'),
    (name: 'Detergent Powder', category: 'Household'),
    (name: 'Dish Soap (Vim)', category: 'Household'),
    (name: 'Floor Cleaner', category: 'Household'),
    (name: 'Toilet Cleaner', category: 'Household'),
    (name: 'Phenyl', category: 'Household'),
    (name: 'Broom (Jhadu)', category: 'Household'),
    (name: 'Garbage Bags', category: 'Household'),
    (name: 'Tissue Paper', category: 'Household'),
    (name: 'Mosquito Repellent', category: 'Household'),
    (name: 'Agarbatti (Incense Sticks)', category: 'Household'),
    (name: 'Matchbox', category: 'Household'),
  ];

  /// Returns suggestions matching [query] (case-insensitive, up to [limit]).
  static List<({String name, String category})> search(
    String query, {
    int limit = 6,
  }) {
    if (query.trim().isEmpty) return const [];
    final q = query.trim().toLowerCase();
    return all
        .where((s) => s.name.toLowerCase().contains(q))
        .take(limit)
        .toList(growable: false);
  }
}
