// GENERATED-STYLE PLACEHOLDER — replace by running `flutterfire configure`.
//
// This file normally is auto-generated by the FlutterFire CLI and contains
// your project's real Firebase keys for each platform. It is committed here
// as a placeholder so the app compiles. See FIREBASE_SETUP.md for steps.
//
// To generate the real file:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// That command overwrites this file with your actual configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run `flutterfire configure` to generate real values.',
        );
    }
  }

  // ---------------------------------------------------------------------------
  // Replace every "REPLACE_ME" below with real values, or (recommended) run
  // `flutterfire configure` which regenerates this whole file for you.
  // ---------------------------------------------------------------------------

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDel-avXb9wG7OtE4-ECtKweqzQy7OrUng',
    appId: '1:964520258094:web:62c9726a4c440b0324cdbf',
    messagingSenderId: '964520258094',
    projectId: 'stock-home-pantry',
    authDomain: 'stock-home-pantry.firebaseapp.com',
    storageBucket: 'stock-home-pantry.firebasestorage.app',
    measurementId: 'G-S46L1G9Y0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZnFLHkPmHfX1Vm6Gx8_djsoNWNqinuhk',
    appId: '1:964520258094:android:3ab277a5f0f2b5d224cdbf',
    messagingSenderId: '964520258094',
    projectId: 'stock-home-pantry',
    storageBucket: 'stock-home-pantry.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmfEj3QaVQhnhpHomNm7JzIYUyd_89xbI',
    appId: '1:964520258094:ios:c3ddce7ec80cf65824cdbf',
    messagingSenderId: '964520258094',
    projectId: 'stock-home-pantry',
    storageBucket: 'stock-home-pantry.firebasestorage.app',
    iosBundleId: 'com.blb.stockhome',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmfEj3QaVQhnhpHomNm7JzIYUyd_89xbI',
    appId: '1:964520258094:ios:61353e3288dfe66324cdbf',
    messagingSenderId: '964520258094',
    projectId: 'stock-home-pantry',
    storageBucket: 'stock-home-pantry.firebasestorage.app',
    iosBundleId: 'com.blb.stockhome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDel-avXb9wG7OtE4-ECtKweqzQy7OrUng',
    appId: '1:964520258094:web:17f2fbb4a86f9bab24cdbf',
    messagingSenderId: '964520258094',
    projectId: 'stock-home-pantry',
    authDomain: 'stock-home-pantry.firebaseapp.com',
    storageBucket: 'stock-home-pantry.firebasestorage.app',
    measurementId: 'G-DW2GHX2PLL',
  );
}
